### ISSUE TITLE
DropdownMenu Flyout position changes based on mousedown duration

### ISSUE THREAD

**Issue by alexandertrefz** [formaat-design/reshaped#298] opened 2024-08-13 08:53 UTC
**Describe the bug**
The positioning of the flyout of the DropdownMenu component depends on how long you click the trigger.

(I suspect this is related to the way the position get calculated relative to the parent, and the fact that the usual buttons scale to be smaller when pressed)

**To Reproduce**
Trigger a DropdownMenu flyout, with something aligned to below it. If you release the click quickly the :active transition will barely start to play, and the aligned object will be fully covered. Hold mousedown and release after a moment and you will see a pixel or 2 of the object peek out.

**Expected behavior**
The flyout should always be at the same position, no matter when the mouse button of the trigger is released.

**Screenshots**

https://github.com/user-attachments/assets/e3149c48-5e10-42ff-bda5-fb941b3edb19

**Environment (please complete the following information):**
 - OS: macOS
 - Browser: Arc (Chromium)
 - Version: 1.55.0 (Chromium Engine Version 127.0.6533.100)

**Additional context**
I have been observing this problem for a little while, I don't think it is browser dependent.

**Comment by blvdmitry** [comment] 2024-08-13 22:56
Yes, I can confirm this is happening because of the button scaling. 

It seems like the most straightforward way to fix the issue is to temporary drop the transition from the trigger when opening a dropdown. Main tradeoff is that it might not work for all types of transitions (e.g. might be noticeable in case it's used with custom long transition), however it would mean the position is calculated correctly.

Other approach I thought about is to calculate the bounds differently (with offsetTop/Left resolving for example), but that would mean positioning will stop respecting any transforms at all, unless those are calculated manually as well.

An example of the 1st approach, wdyt?

https://github.com/user-attachments/assets/bb9cad69-fe3d-4362-bce1-7ee7fe3e292b

**Comment by alexandertrefz** [comment] 2024-08-14 05:37
The button has the correct location on `mousedown`, just not on `mouseup`/`click`, when (I presume) the function that shows the flyout is being called and the location is currently being queried.

Could the correct location not simply be saved upon `mousedown` in some local state, and then used when the Flyout is being shown?

**Comment by blvdmitry** [comment] 2024-08-14 22:08
Fixed it, I think the lazy part of me was speaking before since all bounds calculations were happening outside the component 😅
Now I'm saving the bounds on mousedown for cases when user might click the trigger and using the old way as a fallback.
As a side effect, I've also moved all event handlers to vanilla JS so there will be no potential issues working with the Button where you also need to pass additional React handlers (e.g. for tracking or any other side effect). 

Merging it in a bit, going to be officially announced in 3.2 but will appear in one of the upcoming patch releases as well 

https://github.com/user-attachments/assets/c5f4f022-8267-4149-a223-2acb436f9bb5

**Closed by blvdmitry** 2024-08-14 22:08 UTC
Labels: Type: Bug, Scope: Library
