### ISSUE TITLE
Aria warning when opening popover

### ISSUE THREAD

**Issue by mareksed** [formaat-design/reshaped#335] opened 2024-10-18 13:01 UTC
**Describe the bug**
Occasionaly when opening popover(hover or click) I see this in console.

![CleanShot 2024-10-18 at 14 59 33@2x](https://github.com/user-attachments/assets/36bb087b-45b3-427d-aeb7-9e20e92596a5)

**Comment by blvdmitry** [comment] 2024-10-21 20:36
@mareksed can you still reproduce this after the latest release?

**Comment by mareksed** [comment] 2024-10-21 20:52
https://github.com/user-attachments/assets/8cd5e46b-41c9-4d29-bf8f-2951fb76dfee

try navigating between popover position section and trigger popover from usage section.
not the easiest thing to reproduce, but in general I see this warning a lot during development with popovers.
I was not able to crack the pattern, why is it so.

**Comment by blvdmitry** [comment] 2024-10-21 22:37
A stable reproduction I found was Open a clickable popover, open a hoverable popover, click on the hoverable popover trigger.
It was happening because screen reader trap inside the focus trap was trying to initialize even when there are no elements to focus, so it had issues cleaning up attributes later on. Fixed now for the next patch.

**Closed by blvdmitry** 2024-10-21 22:37 UTC
Labels: Type: Bug, Scope: Library
