### ISSUE TITLE
Neutral faded button doesn't seem right

### ISSUE THREAD

**Issue by b-graves** [formaat-design/reshaped#223] opened 2024-02-28 16:36 UTC
Hi, 

I have been using the faded buttons in my UI design, however I've found that the neutral color does not quite fit with the other faded variants. The current version to me feels like the outlined variant rather than the other faded ones. Please see below the current versions of the buttons compared to what I would have expected

![image](https://github.com/formaat-design/reshaped/assets/56936483/601bf432-70a7-4292-a00d-c0a0b5918c8c)

![image](https://github.com/formaat-design/reshaped/assets/56936483/47b572f5-be4a-49b1-ab68-89e03a4b5b9a)

I would have expected it to be neutral faded background and no border.

Here is an example of our UI where we have a set of faded buttons, but the neutral one doesn't sit with the others:

![image](https://github.com/formaat-design/reshaped/assets/56936483/e0028859-9724-418a-b007-642a70c5bb10)

and now with my suggested changes:

![image](https://github.com/formaat-design/reshaped/assets/56936483/2c8fb940-6ea7-411b-ad18-b72dbd805e8f)

I would be interested to know why you decided to go for the style you chose for this button and what you think about the idea of changing it to be more similar to the others.

Thanks!
Ben

**Comment by blvdmitry** [comment] 2024-02-28 21:27
Hey, it's actually working as intended but I agree with you that it doesn't seem to be quite logical. It was basically a trade-off we assumed trying to address 2 challenges at once:
- We needed an outline button variant with softer borders that can still guarantee contrast due to using a background color (aligned with the cards borders)
- Neutral faded background is not too different from the regular neutral button, compared to other button colors so it felt repeating itself a bit if there are 2 variants with similar color values

We're planning to revisit the button variants for the next major release, where we might change how outline buttons behave and align them closer to inputs by making the inputs borders softer too

**Comment by blvdmitry** [comment] 2024-04-17 17:41
Going to be resolved in https://github.com/orgs/formaat-design/projects/2/views/1?pane=issue&itemId=58597261 so I'll close the issue as a duplicate for now

We're starting to work on it now and we're planning to release canary releases as we approach 3.0 in case someone wants to access specific parts earlier

**Closed by blvdmitry** 2024-04-17 17:41 UTC
